<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-23 at 10:34:37.
 */
class FindDateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FindDate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FindDate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FindDate::find_date
     * @todo   Implement testFind_date().
     */
    public function testFind_date()
    {
        $this->object->format = 'YYYYMMDD';
        $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 2012/01/01. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 11-12-30. Will it work?'));
        $this->assertEquals(array('day' => '02', 'month' => '01', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1985 1 2. Will it work?'));
        $this->assertEquals(array('day' => '12', 'month' => '10', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 1850.10.12. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 85 12 5. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 2012 October 5. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1985 MAY 5th . Will it work?'));
        $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 81 March 1st. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => 'a'), $this->object->find('This is a test 11-12-30a. Will it work?'));
        $this->assertEquals(array('day' => '02', 'month' => '01', 'year' => '1985', 'meridiem' => 'pm'), $this->object->find('This is a test 1985 1 2 pm. Will it work?'));
        $this->assertEquals(array('day' => '12', 'month' => '10', 'year' => '1850', 'meridiem' => 'A'), $this->object->find('This is a test 1850.10.12A. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => 'AM'), $this->object->find('This is a test 85 12 5AM. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => 'PM'), $this->object->find('This is a test 2012 October 5PM. Will it work?'));
        // Fails with th at end
        // $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => 'morning'), $this->object->find('This is a test 1985 MAY 5th morning. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => 'Evening'), $this->object->find('This is a test 81 March 1st Evening. Will it work?'));

        $this->object->format = 'YYYYMD';
        $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 2012/01/01. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 11-12-30. Will it work?'));
        $this->assertEquals(array('day' => '02', 'month' => '01', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1985 1 2. Will it work?'));
        $this->assertEquals(array('day' => '12', 'month' => '10', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 1850.10.12. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 85 12 5. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 2012 October 5. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1985 MAY 5th . Will it work?'));
        $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 81 March 1st. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => 'a'), $this->object->find('This is a test 11-12-30a. Will it work?'));
        $this->assertEquals(array('day' => '02', 'month' => '01', 'year' => '1985', 'meridiem' => 'pm'), $this->object->find('This is a test 1985 1 2 pm. Will it work?'));
        $this->assertEquals(array('day' => '12', 'month' => '10', 'year' => '1850', 'meridiem' => 'A'), $this->object->find('This is a test 1850.10.12A. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => 'AM'), $this->object->find('This is a test 85 12 5AM. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => 'PM'), $this->object->find('This is a test 2012 October 5PM. Will it work?'));

        $this->object->format = 'DDMMYYYY';
        $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 01/01/2012. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 30-12-11. Will it work?'));
        $this->assertEquals(array('day' => '01', 'month' => '02', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1 2 1985. Will it work?'));
        $this->assertEquals(array('day' => '10', 'month' => '12', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 10.12.1850. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 5 12 85. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 5 October 2012. Will it work?'));
        //M D Y
        // $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test MAY 5th 1985. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 1st March 81. Will it work?'));
        
        $this->object->format = 'DMYYYY';
        $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 01/01/2012. Will it work?'));
        $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 30-12-11. Will it work?'));
        $this->assertEquals(array('day' => '01', 'month' => '02', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1 2 1985. Will it work?'));
        $this->assertEquals(array('day' => '10', 'month' => '12', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 10.12.1850. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 5 12 85. Will it work?'));
        $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 5 October 2012. Will it work?'));
        //M D Y
        // $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test MAY 5th 1985. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 1st March 81. Will it work?'));
        
        // $this->object->format = 'MMDDYYYY';
        // $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 01/01/2012. Will it work?'));
        // $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 30-12-11. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '02', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1 2 1985. Will it work?'));
        // $this->assertEquals(array('day' => '10', 'month' => '12', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 10.12.1850. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 5 12 85. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 5 October 2012. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test MAY 5th 1985. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 1st March 81. Will it work?'));

        // $this->object->format = 'MDYYYY';
        // $this->assertEquals(array('day' => '01', 'month' => '01', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 01/01/2012. Will it work?'));
        // $this->assertEquals(array('day' => '30', 'month' => '12', 'year' => '2011', 'meridiem' => ''), $this->object->find('This is a test 30-12-11. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '02', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 1 2 1985. Will it work?'));
        // $this->assertEquals(array('day' => '10', 'month' => '12', 'year' => '1850', 'meridiem' => ''), $this->object->find('This is a test 10.12.1850. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '12', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test 5 12 85. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '10', 'year' => '2012', 'meridiem' => ''), $this->object->find('This is a test 5 October 2012. Will it work?'));
        // $this->assertEquals(array('day' => '05', 'month' => '05', 'year' => '1985', 'meridiem' => ''), $this->object->find('This is a test MAY 5th 1985. Will it work?'));
        // $this->assertEquals(array('day' => '01', 'month' => '03', 'year' => '1981', 'meridiem' => ''), $this->object->find('This is a test 1st March 81. Will it work?'));


    }
}
